env: CUCUMBER_FORMAT=progress
bundler_args: --without extras
script: "bundle exec rspec spec/vcr/library_hooks/excon_spec.rb"
rvm:
  - 1.8.7
  - 1.9.2
branches:
  only:
    - master
    - 1-x-stable
    - travis-testing

